### ISSUE TITLE
Additional IoT hub features

### ISSUE THREAD

**Issue by onionhammer** [andriyadi/AzureIoTHubMQTTClient#4]
Would be nice to see device twins and an overload to parse a standard iot hub connection string. Any roadmap?

**Comment by andriyadi** [comment]
Hi @onionhammer 
I saw your PR and merged it. Thanks!

Currently I don't have enough time to manage this repo and no definitive roadmap yet, but let's see what I can do. So, you're welcome to contribute.

**Comment by onionhammer** [comment]
Thanks, I might.
